# Generated by Django 3.2.20 on 2023-08-09 19:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20230809_1414'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0004_alter_bookmark_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('owner', 'book')},
        ),
    ]
