# Generated by Django 3.2.20 on 2023-08-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='../No_image_available.svg_t2xrtz.png', upload_to='images/'),
        ),
    ]
